# Generated by Django 4.1 on 2023-11-21 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conta_agencia', models.CharField(default=9090, max_length=5)),
                ('conta_numero', models.CharField(max_length=20, unique=True)),
                ('conta_tipo', models.CharField(default='Standart', max_length=20)),
                ('conta_limite', models.FloatField(max_length=20)),
                ('conta_saldo', models.FloatField(default=0.0, max_length=20)),
                ('conta_ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sobrenome', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('senha', models.CharField(max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(max_length=20)),
                ('observacao', models.TextField(blank=True, max_length=100)),
                ('tipo_transferencia', models.CharField(max_length=20)),
                ('conta_id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_id_destino', to='api.conta')),
                ('conta_id_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_id_origem', to='api.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movimentacao_valor', models.FloatField()),
                ('movimentacao_observacao', models.TextField(max_length=100)),
                ('conta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investimento_aporte', models.FloatField()),
                ('investimento_prazo', models.DateField(blank=True)),
                ('investimento_observacao', models.TextField(max_length=100)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_logradouro', models.CharField(max_length=10)),
                ('endereco_bairro', models.CharField(max_length=30)),
                ('endereco_cidade', models.CharField(max_length=30)),
                ('endereco_rua', models.CharField(max_length=20)),
                ('endereco_uf', models.CharField(max_length=2)),
                ('endereco_cep', models.CharField(max_length=8)),
                ('cliente_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emprestimo_valor', models.FloatField()),
                ('emprestimo_juros', models.FloatField()),
                ('emprestimo_quantidade_parcelas', models.IntegerField()),
                ('emprestimo_observacao', models.TextField(max_length=100)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contato_numero', models.CharField(max_length=15, unique=True)),
                ('contato_email', models.EmailField(max_length=50, unique=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='ClientePj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_cnpj', models.CharField(max_length=25)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=11)),
                ('cliente_pj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_cpf', models.CharField(max_length=15, unique=True)),
                ('cliente_rg', models.CharField(max_length=15, unique=True)),
                ('cliente_pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cartao_numero', models.CharField(max_length=19, unique=True)),
                ('cartao_cvv', models.CharField(max_length=3)),
                ('cartao_validade', models.DateField()),
                ('cartao_bandeira', models.CharField(max_length=20)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
            ],
        ),
    ]
