# Generated by Django 4.1 on 2023-11-25 20:34

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('url_image', models.ImageField(null=True, upload_to=api.models.user_image_field)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conta_agencia', models.CharField(default=9090, max_length=4)),
                ('conta_numero', models.CharField(max_length=8, unique=True)),
                ('conta_tipo', models.CharField(default='Standart', max_length=20)),
                ('conta_saldo', models.FloatField(default=0.0, max_length=20)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(max_length=20)),
                ('observacao', models.TextField(blank=True, max_length=100)),
                ('tipo_transferencia', models.CharField(max_length=20)),
                ('conta_id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_id_destino', to='api.conta')),
                ('conta_id_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_id_origem', to='api.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movimentacao_valor', models.FloatField()),
                ('movimentacao_observacao', models.TextField(max_length=100)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investimento_aporte', models.FloatField()),
                ('investimento_prazo', models.DateField(blank=True)),
                ('investimento_observacao', models.TextField(max_length=100)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_logradouro', models.CharField(max_length=10)),
                ('endereco_bairro', models.CharField(max_length=30)),
                ('endereco_cidade', models.CharField(max_length=30)),
                ('endereco_rua', models.CharField(max_length=20)),
                ('endereco_uf', models.CharField(max_length=2)),
                ('endereco_cep', models.CharField(max_length=8)),
                ('cliente_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emprestimo_valor', models.FloatField()),
                ('emprestimo_juros', models.FloatField()),
                ('emprestimo_quantidade_parcelas', models.IntegerField()),
                ('emprestimo_observacao', models.TextField(max_length=100)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contato_numero', models.CharField(max_length=15, unique=True)),
                ('contato_email', models.EmailField(max_length=50, unique=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_cnpj', models.CharField(max_length=25)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=11)),
                ('cliente_pj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_cpf', models.CharField(max_length=15, unique=True)),
                ('cliente_rg', models.CharField(max_length=15, unique=True)),
                ('cliente_pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cartao_numero', models.CharField(max_length=19, unique=True)),
                ('cartao_cvv', models.CharField(max_length=3)),
                ('cartao_validade', models.DateField()),
                ('cartao_bandeira', models.CharField(max_length=20)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
            ],
        ),
    ]
